version: '3'
services:
  web:
    build: ./
    ports:
      - "85:80"
    depends_on:
      - db
    expose:
      - 9010
    volumes:
      - ./:/var/www/html/
      - ./config/php.ini:/usr/local/etc/php/php.ini
      - ./config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - ecomSy_network

  db:
    image: mysql
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecomSy_db
      MYSQL_USER: badr
      MYSQL_PASSWORD: 123456
    volumes:
      - "./db:/var/lib/mysql"
    networks:
      - ecomSy_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8880:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - ecomSy_network

networks:
  ecomSy_network:
    driver: bridge
