index:
   path: /
   controller: App\Controller\TestController::index

# test:
#    path: /test/{age<\d+>?0}
#    controller: App\Controller\TestController::test
#    methods: [GET, POST]
#    host: localhost
#    schemes: [https, https]
   #  host: {subdomaine}.monsite.com
  #  defaults:
  #    age: 0
  #  requirements:
  #    age: \d+