<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZLGbLZL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZLGbLZL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZLGbLZL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZLGbLZL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZLGbLZL\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZLGbLZL',
    'container.build_id' => '54748e53',
    'container.build_time' => 1663364564,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZLGbLZL');
