<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQb0xbHk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQb0xbHk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQb0xbHk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQb0xbHk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQb0xbHk\App_KernelDevDebugContainer([
    'container.build_hash' => 'Qb0xbHk',
    'container.build_id' => 'd0245792',
    'container.build_time' => 1664140803,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQb0xbHk');
