<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIa0qxjU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIa0qxjU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIa0qxjU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIa0qxjU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIa0qxjU\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ia0qxjU',
    'container.build_id' => '7159472c',
    'container.build_time' => 1665074736,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIa0qxjU');
