<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'hello' => [['nom'], ['nom' => 'world', '_controller' => 'App\\Controller\\HelloController::hello'], [], [['variable', '/', '[^/]++', 'nom', true], ['text', '/hello']], [], []],
    'test' => [['age'], ['age' => '0', '_controller' => 'App\\Controller\\TestController::test'], ['age' => '\\d+'], [['variable', '/', '\\d+', 'age', true], ['text', '/test']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\TestController::index'], [], [['text', '/']], [], []],
];
